export const DEFAULT_TOOLS = [
  // ── ANALİZ ──────────────────────────────────────────────────────────────────
  { id:'doc_analyze',      cat:'Analiz',        icon:'📄', label:'Doküman Analizi',           desc:'Belge/metin → gereksinimleri çıkar',            color:'blue'   },
  { id:'error_analyze',    cat:'Analiz',        icon:'🐛', label:'Hata Analizi',               desc:'Stack trace/hata → root cause + çözüm',         color:'red'    },
  { id:'code_review',      cat:'Analiz',        icon:'🔬', label:'Kod İnceleme',               desc:'Kod parçası → test edilmesi gereken alanlar',   color:'blue'   },
  { id:'risk_assess',      cat:'Analiz',        icon:'⚠️', label:'Risk Değerlendirme',         desc:'Özellik/değişiklik → risk analizi',             color:'orange' },
  { id:'req_extract',      cat:'Analiz',        icon:'📋', label:'Gereksinim Çıkarma',         desc:'Ham metin → yapılandırılmış gereksinimler',     color:'blue'   },
  { id:'db_test',          cat:'Analiz',        icon:'🗄', label:'Veritabanı Test Senaryosu',   desc:'DB şeması → veri bütünlüğü ve sorgu testleri',  color:'blue'   },
  { id:'impact_analyze',   cat:'Analiz',        icon:'🌊', label:'Etki Analizi',               desc:'Değişiklik → etkilenen modülleri ve riskleri analiz et', color:'orange' },
  { id:'root_cause',       cat:'Analiz',        icon:'🔍', label:'Kök Neden Analizi',          desc:'Hata → 5-Why ve balık kılçığı yöntemi',         color:'red'    },
  { id:'test_coverage',    cat:'Analiz',        icon:'📐', label:'Test Kapsamı Değerlendir',   desc:'Mevcut testler → boşluk analizi ve öneriler',   color:'teal'   },
  // ── SENARYO ÜRET ────────────────────────────────────────────────────────────
  { id:'scenario_web',     cat:'Senaryo Üret',  icon:'🌐', label:'Web Test Senaryosu',         desc:'Web uygulaması → E2E test adımları',            color:'purple' },
  { id:'scenario_mobile',  cat:'Senaryo Üret',  icon:'📱', label:'Mobil Test Senaryosu',       desc:'Mobil uygulama → test senaryoları',             color:'purple' },
  { id:'scenario_api',     cat:'Senaryo Üret',  icon:'🔌', label:'API Test Senaryosu',         desc:'Endpoint/API → pozitif & negatif testler',      color:'purple' },
  { id:'scenario_desktop', cat:'Senaryo Üret',  icon:'🖥️', label:'Desktop/EXE Senaryosu',     desc:'Masaüstü uygulama → otomasyon adımları',        color:'purple' },
  { id:'scenario_perf',    cat:'Senaryo Üret',  icon:'⚡', label:'Performans Senaryosu',       desc:'Yük/stres test planı oluştur',                  color:'yellow' },
  { id:'bdd_write',        cat:'Senaryo Üret',  icon:'🥒', label:'BDD / Gherkin Yaz',          desc:'Özellik → Given/When/Then formatı',             color:'green'  },
  { id:'negative_tests',   cat:'Senaryo Üret',  icon:'❌', label:'Negatif Test Üret',          desc:'Normal akış → edge case & hata senaryoları',    color:'red'    },
  { id:'scenario_embedded',cat:'Senaryo Üret',  icon:'⚙️', label:'Gömülü Sistem Senaryosu',   desc:'Firmware/donanım → entegrasyon test adımları',  color:'teal'   },
  { id:'scenario_protocol',cat:'Senaryo Üret',  icon:'📡', label:'Protokol Test Senaryosu',    desc:'Haberleşme protokolü → uyumluluk testleri',     color:'blue'   },
  { id:'scenario_failover',cat:'Senaryo Üret',  icon:'🔃', label:'Failover / Dayanıklılık',    desc:'Sistem → kesinti ve kurtarma test senaryoları', color:'orange' },
  // ── OTOMASYON ───────────────────────────────────────────────────────────────
  { id:'playwright_gen',   cat:'Otomasyon',     icon:'🎭', label:'Playwright Script',           desc:'Senaryo → hazır Playwright kodu',               color:'teal'   },
  { id:'pytest_gen',       cat:'Otomasyon',     icon:'🐍', label:'pytest Kodu',                 desc:'Test senaryosu → pytest fonksiyonları',         color:'teal'   },
  { id:'postman_gen',      cat:'Otomasyon',     icon:'📮', label:'Postman Koleksiyonu',         desc:'API → Postman test koleksiyonu JSON',           color:'orange' },
  { id:'ci_pipeline',      cat:'Otomasyon',     icon:'🔄', label:'CI/CD Pipeline',              desc:'Testler → GitHub Actions YAML',                 color:'teal'   },
  { id:'mock_data',        cat:'Otomasyon',     icon:'🎲', label:'Test Verisi Üret',            desc:'Şema/alan → gerçekçi test verisi',              color:'teal'   },
  { id:'microservice_test',cat:'Otomasyon',     icon:'🧩', label:'Mikroservis Test',            desc:'Servis → bağımsız ve entegrasyon testleri',     color:'teal'   },
  { id:'selenium_gen',     cat:'Otomasyon',     icon:'🤖', label:'Selenium Script',             desc:'Senaryo → Python Selenium kodu',                color:'green'  },
  { id:'appium_gen',       cat:'Otomasyon',     icon:'📲', label:'Appium Script',               desc:'Mobil senaryo → Appium test kodu',              color:'purple' },
  { id:'robot_gen',        cat:'Otomasyon',     icon:'🦾', label:'Robot Framework',             desc:'Test adımları → Robot Framework keyword kodu', color:'blue'   },
  { id:'jmeter_gen',       cat:'Otomasyon',     icon:'📊', label:'JMeter Test Planı',           desc:'Yük senaryosu → JMeter .jmx dosyası',           color:'orange' },
  { id:'k6_gen',           cat:'Otomasyon',     icon:'🚀', label:'k6 Performans Scripti',       desc:'Yük testi → k6 JavaScript kodu',                color:'yellow' },
  { id:'docker_test',      cat:'Otomasyon',     icon:'🐳', label:'Docker Test Ortamı',          desc:'Proje → Docker Compose test yapılandırması',    color:'teal'   },
  // ── DOKÜMAN ─────────────────────────────────────────────────────────────────
  { id:'checklist',        cat:'Doküman',       icon:'✅', label:'Test Kontrol Listesi',        desc:'Konu → kapsamlı QA checklist',                  color:'green'  },
  { id:'test_plan',        cat:'Doküman',       icon:'📝', label:'Test Planı',                  desc:'Proje → resmi test planı belgesi',               color:'green'  },
  { id:'bug_report',       cat:'Doküman',       icon:'🐞', label:'Bug Raporu Yaz',              desc:'Sorun açıkla → standart bug raporu',             color:'red'    },
  { id:'test_summary',     cat:'Doküman',       icon:'📊', label:'Test Özet Raporu',            desc:'Test sonuçları → yönetici özeti',                color:'green'  },
  { id:'test_matrix',      cat:'Doküman',       icon:'🗂️', label:'Test Matrisi',               desc:'Özellikler × test tipleri matrisi',              color:'green'  },
  { id:'install_test',     cat:'Doküman',       icon:'📦', label:'Kurulum/Deployment Testi',    desc:'Uygulama → kurulum ve dağıtım test adımları',   color:'green'  },
  { id:'test_strategy',    cat:'Doküman',       icon:'🗺️', label:'Test Stratejisi',            desc:'Proje → üst düzey test yaklaşımı belgesi',      color:'blue'   },
  { id:'test_case_doc',    cat:'Doküman',       icon:'📑', label:'Test Vakası Belgesi',         desc:'Senaryo → formal test case dokümanı',            color:'teal'   },
  { id:'traceability',     cat:'Doküman',       icon:'🔗', label:'İzlenebilirlik Matrisi',      desc:'Gereksinim ↔ test case bağlantı matrisi',       color:'purple' },
  { id:'release_note',     cat:'Doküman',       icon:'📢', label:'Sürüm Test Notu',             desc:'Sürüm → test sonuçları ve bilinen sorunlar',     color:'yellow' },
  // ── KALİTE ──────────────────────────────────────────────────────────────────
  { id:'coverage_check',   cat:'Kalite',        icon:'🎯', label:'Coverage Analizi',            desc:'Mevcut testler → eksik alanları bul',            color:'pink'   },
  { id:'accessibility',    cat:'Kalite',        icon:'♿', label:'Erişilebilirlik Testi',       desc:'Arayüz → WCAG kontrol listesi',                  color:'pink'   },
  { id:'security_test',    cat:'Kalite',        icon:'🔒', label:'Güvenlik Testi',              desc:'Uygulama → OWASP bazlı güvenlik testleri',       color:'pink'   },
  { id:'ux_test',          cat:'Kalite',        icon:'🎨', label:'UX Test Senaryosu',           desc:'Akış → kullanıcı deneyimi test adımları',        color:'pink'   },
  { id:'regression',       cat:'Kalite',        icon:'🔁', label:'Regresyon Test Seti',         desc:'Değişiklik → etkilenen regresyon testleri',      color:'yellow' },
  { id:'email_test',       cat:'Kalite',        icon:'📧', label:'E-posta/Bildirim Testi',      desc:'Bildirim akışı → e-posta doğrulama testleri',    color:'pink'   },
  { id:'perf_analyze',     cat:'Kalite',        icon:'⏱️', label:'Performans Analizi',         desc:'Metrikler → darboğaz ve iyileştirme önerileri',  color:'orange' },
  { id:'usability_test',   cat:'Kalite',        icon:'👥', label:'Kullanılabilirlik Testi',     desc:'Arayüz → kullanıcı dostu tasarım kontrolleri',   color:'blue'   },
  { id:'compliance_test',  cat:'Kalite',        icon:'📜', label:'Uyumluluk / Standart Testi', desc:'Sistem → standart ve mevzuat uygunluk kontrolü', color:'teal'   },
  // ── SAVUNMA SANAYİİ ─────────────────────────────────────────────────────────
  { id:'def_sys_test',     cat:'Savunma',       icon:'🛡️', label:'Sistem Doğrulama Testi',     desc:'Savunma sistemi → V&V test planı',               color:'red'    },
  { id:'def_req_verify',   cat:'Savunma',       icon:'📌', label:'Gereksinim Doğrulama',        desc:'SRS/IRS → gereksinim izlenebilirlik analizi',    color:'orange' },
  { id:'def_int_test',     cat:'Savunma',       icon:'🔧', label:'Entegrasyon Test Planı',      desc:'Alt sistemler → sistem entegrasyon test planı',  color:'teal'   },
  { id:'def_env_test',     cat:'Savunma',       icon:'🌡️', label:'Çevresel Test Planı',        desc:'MIL-STD-810 → termal/titreşim/nem test planı',  color:'yellow' },
  { id:'def_interface',    cat:'Savunma',       icon:'🔗', label:'Arayüz Test Senaryosu',       desc:'ICD/IRS → arayüz doğrulama test adımları',      color:'blue'   },
  { id:'def_safety',       cat:'Savunma',       icon:'⚕️', label:'Güvenlik Kritiklik Analizi', desc:'Sistem → emniyet kritik fonksiyon analizi',      color:'red'    },
  { id:'def_protocol_test',cat:'Savunma',       icon:'📡', label:'MIL Protokol Testi',          desc:'MIL-STD-1553/ARINC → veri yolu test senaryosu', color:'purple' },
  { id:'def_fat',          cat:'Savunma',       icon:'🏭', label:'FAT / SAT Test Planı',        desc:'Fabrika/saha kabul testi prosedürü oluştur',     color:'green'  },
  { id:'def_regression',   cat:'Savunma',       icon:'🔄', label:'Savunma Regresyon Testi',     desc:'Yazılım güncelleme → etkilenen test setleri',    color:'orange' },
  { id:'def_cybersec',     cat:'Savunma',       icon:'🔐', label:'Siber Güvenlik Testi',        desc:'Sistem → TEMPEST/sızma test senaryoları',        color:'red'    },
]

export const CATEGORIES = ['Analiz', 'Senaryo Üret', 'Otomasyon', 'Doküman', 'Kalite', 'Savunma']

export const PRESETS = [
  { label:'🚀 Hızlı Başlangıç',   tools:['doc_analyze','checklist','scenario_web'] },
  { label:'🔒 Güvenlik Odaklı',   tools:['risk_assess','security_test','negative_tests'] },
  { label:'🤖 Tam Otomasyon',     tools:['scenario_web','playwright_gen','ci_pipeline'] },
  { label:'📋 Tam Doküman Seti',  tools:['test_plan','checklist','bug_report','test_matrix'] },
  { label:'🐛 Hata Ayıklama',     tools:['error_analyze','root_cause','bug_report','regression'] },
  { label:'🌐 API Test Paketi',   tools:['scenario_api','postman_gen','mock_data','security_test'] },
  { label:'🛡️ Savunma V&V',      tools:['def_sys_test','def_req_verify','def_int_test','traceability'] },
  { label:'⚡ Performans Paketi', tools:['scenario_perf','jmeter_gen','k6_gen','perf_analyze'] },
]

export const PALETTE = {
  blue:   { bg:'rgba(56,189,248,0.09)',  border:'rgba(56,189,248,0.30)',  text:'#38bdf8',  sel:'rgba(56,189,248,0.18)'  },
  purple: { bg:'rgba(167,139,250,0.09)', border:'rgba(167,139,250,0.30)', text:'#a78bfa',  sel:'rgba(167,139,250,0.18)' },
  green:  { bg:'rgba(52,211,153,0.09)',  border:'rgba(52,211,153,0.30)',  text:'#34d399',  sel:'rgba(52,211,153,0.18)'  },
  teal:   { bg:'rgba(45,212,191,0.09)',  border:'rgba(45,212,191,0.30)',  text:'#2dd4bf',  sel:'rgba(45,212,191,0.18)'  },
  orange: { bg:'rgba(251,146,60,0.09)',  border:'rgba(251,146,60,0.30)',  text:'#fb923c',  sel:'rgba(251,146,60,0.18)'  },
  yellow: { bg:'rgba(250,204,21,0.09)',  border:'rgba(250,204,21,0.30)',  text:'#facc15',  sel:'rgba(250,204,21,0.18)'  },
  red:    { bg:'rgba(248,113,113,0.09)', border:'rgba(248,113,113,0.30)', text:'#f87171',  sel:'rgba(248,113,113,0.18)' },
  pink:   { bg:'rgba(244,114,182,0.09)', border:'rgba(244,114,182,0.30)', text:'#f472b6',  sel:'rgba(244,114,182,0.18)' },
  gold:   { bg:'rgba(251,191,36,0.09)',  border:'rgba(251,191,36,0.30)',  text:'#fbbf24',  sel:'rgba(251,191,36,0.18)'  },
  cyan:   { bg:'rgba(34,211,238,0.09)',  border:'rgba(34,211,238,0.30)',  text:'#22d3ee',  sel:'rgba(34,211,238,0.18)'  },
  lime:   { bg:'rgba(163,230,53,0.09)',  border:'rgba(163,230,53,0.30)',  text:'#a3e635',  sel:'rgba(163,230,53,0.18)'  },
  rose:   { bg:'rgba(251,113,133,0.09)', border:'rgba(251,113,133,0.30)', text:'#fb7185',  sel:'rgba(251,113,133,0.18)' },
  slate:  { bg:'rgba(148,163,184,0.09)', border:'rgba(148,163,184,0.30)', text:'#94a3b8',  sel:'rgba(148,163,184,0.18)' },
  indigo: { bg:'rgba(99,102,241,0.09)',  border:'rgba(99,102,241,0.30)',  text:'#6366f1',  sel:'rgba(99,102,241,0.18)'  },
}

export function buildPrompt(toolId, input, customPrompt) {
  if (customPrompt) return customPrompt + '\n\nGirdi:\n' + input
  const base = 'Turkce yanıtla. Sade ve anlasılır ol.\n\nGirdi:\n' + input + '\n\n'
  const map = {
    doc_analyze:       base + 'Bu dokumani analiz et: 1) Ozet 2) Ana gereksinimler 3) Test edilmesi gereken senaryolar 4) Riskli alanlar',
    error_analyze:     base + 'Bu hatayı analiz et: 1) Ne anlama geliyor 2) Muhtemel nedenler 3) Cozum adımları 4) Test senaryosu',
    code_review:       base + 'Bu kodu test acısından incele: 1) Kritik noktalar 2) Riskli alanlar 3) Eksik edge caseler 4) Test onerileri',
    risk_assess:       base + 'Risk degerlendirmesi yap: 1) Yuksek riskli alanlar 2) Orta risk 3) Dusuk risk 4) Test oncelikleri',
    req_extract:       base + 'Gereksinimleri cikar: fonksiyonel, fonksiyonel olmayan, belirsiz noktalar, test kriterleri',
    db_test:           base + 'Veritabanı test senaryoları: veri butunlugu, CRUD islemleri, iliskisel kısıtlar, performans sorguları',
    impact_analyze:    base + 'Etki analizi yap: hangi moduller etkilenir, regresyon riski, test onceligi, degisiklik kapsamı',
    root_cause:        base + '5-Why ve balık kılcıgı yontemiyle kok neden analizi yap. Duzeltici ve onleyici aksiyonları listele',
    test_coverage:     base + 'Test kapsam analizi: hangi alanlar test ediliyor, hangileri eksik, risk bazlı oncelik onerileri',
    scenario_web:      base + 'Web uygulaması icin test senaryoları: pozitif, negatif, edge case. Ad, On kosul, Adımlar, Beklenen sonuc',
    scenario_mobile:   base + 'Mobil uygulama test senaryoları: iOS/Android farkları, dokunmatik, ag kosulları, izinler',
    scenario_api:      base + 'API test senaryoları: basarılı yanıtlar, hata kodları, sınır degerleri, kimlik dogrulama, rate limiting',
    scenario_desktop:  base + 'Masaustu/EXE test senaryoları: kurulum, UI etkilesimleri, dosya islemleri, sistem entegrasyonu',
    scenario_perf:     base + 'Performans test planı: yuk testi, stres testi, dayanıklılık. Metrikler ve esik degerleri',
    bdd_write:         base + 'BDD formatında (Given/When/Then) Gherkin senaryoları yaz. Feature dosyası formatında',
    negative_tests:    base + 'Negatif ve edge case testler: gecersiz girisler, sınır degerleri, bos degerler',
    scenario_embedded: base + 'Gomulu sistem test senaryoları: firmware entegrasyonu, donen surede yanıt, donanım-yazılım ara yuzu testleri',
    scenario_protocol: base + 'Protokol uyumluluk test senaryoları: mesaj formatı, zamanlama, hata islemesi, edge case',
    scenario_failover: base + 'Failover ve dayanıklılık test senaryoları: birincil sistem arızası, otomatik gecis, veri tutarlılıgı',
    playwright_gen:    base + 'Playwright (TypeScript) test kodu yaz. Gercekci selectorlar, bekleme mekanizmaları ve assertionlar',
    pytest_gen:        base + 'pytest test fonksiyonları yaz. Fixturelar, parametrize ve assertionlar dahil',
    postman_gen:       base + 'Postman koleksiyonu JSON formatında yaz. Test scriptleri ve environment degiskenleri',
    ci_pipeline:       base + 'GitHub Actions YAML pipeline yaz. Test kosturma, raporlama ve bildirim adımları',
    mock_data:         base + 'Gercekci test verisi uret. Gecerli/gecersiz ornekler, sınır degerleri',
    microservice_test: base + 'Mikroservis test senaryoları: servis bagimsızlıgı, API sozlesmesi, hata toleransı',
    selenium_gen:      base + 'Python Selenium test kodu yaz. WebDriverManager, Page Object Model, assertionlar dahil',
    appium_gen:        base + 'Appium Python test kodu yaz. iOS/Android icin desired capabilities, element bulma, assertion',
    robot_gen:         base + 'Robot Framework keyword-driven test kodu yaz. Resource dosyası ve test suite formatında',
    jmeter_gen:        base + 'JMeter test planı XML (.jmx) formatında yaz. Thread group, HTTP sampler, assertion, listener dahil',
    k6_gen:            base + 'k6 performans test scripti JavaScript formatında yaz. VU, ramp-up, threshold ve metrik kontrolleri',
    docker_test:       base + 'Docker Compose test ortamı YAML dosyası yaz. Servisler, ag, volume ve saglik kontrolleri',
    checklist:         base + 'Kapsamlı test kontrol listesi. Her madde icin checkbox. Fonksiyonel, performans, guvenlik, kullanılabilirlik',
    test_plan:         base + 'Resmi test planı: kapsam, yaklasım, kaynaklar, zamanlama, giris/cıkıs kriterleri, riskler',
    bug_report:        base + 'Standart bug raporu: baslik, ozet, adımlar, beklenen/gerceklesen sonuc, ortam bilgisi, oncelik',
    test_summary:      base + 'Yonetici duzeyinde test ozet raporu: toplam/gecen/kalan, kapsam, kritik bulgular, tavsiyeler',
    test_matrix:       base + 'Test matrisi: ozellikler x test tipleri (birim/entegrasyon/e2e/guvenlik/performans). Tablo formatında',
    install_test:      base + 'Kurulum ve deployment test adımları: on kosullar, kurulum, yapılandırma, smoke testler, geri alma planı',
    test_strategy:     base + 'Ust duzey test stratejisi belgesi: vizyon, kapsam, yaklasım, araclar, metrikler, takvim',
    test_case_doc:     base + 'Formal test case belgesi: TC ID, baslik, on kos¸ul, adımlar, beklenen sonuc, oncelik, durum',
    traceability:      base + 'Gereksinim-test case izlenebilirlik matrisi: her gereksinim icin kapsayan test caseleri tablola',
    release_note:      base + 'Surum test notu: yeni ozellikler, duzeltilen hatalar, bilinen sorunlar, test kapsamı, tavsiye',
    coverage_check:    base + 'Test coverage analizi: hangi alanlar kapsanmıs, hangileri eksik, oncelikli bosluklar',
    accessibility:     base + 'WCAG 2.1 bazlı erisebilirlik test listesi: klavye erisimi, ekran okuyucu, renk kontrastı',
    security_test:     base + 'OWASP Top 10 bazlı guvenlik test senaryoları: SQL injection, XSS, CSRF, kimlik dogrulama',
    ux_test:           base + 'UX test senaryoları: kullanıcı akısları, hata mesajları, navigasyon, mobil uyumluluk',
    regression:        base + 'Regresyon test seti: degisiklikten etkilenebilecek alanlar, kritik smoke testler, oncelik sırası',
    email_test:        base + 'E-posta ve bildirim testleri: gonderim dogrulaması, icerik kontrolu, HTML render, mobil uyumluluk',
    perf_analyze:      base + 'Performans analizi: darbogazlar, yanıt suresi, kaynak kullanımı, iyilestirme onerileri',
    usability_test:    base + 'Kullanılabilirlik test senaryoları: gorev tamamlama, hata kurtarma, ogrenme kolaylıgı',
    compliance_test:   base + 'Uyumluluk test senaryoları: ilgili standart ve yonetmelik gereksinimlerini dogrulayan test adımları',
    def_sys_test:      base + 'Savunma sistemi V&V test planı: dogrulama ve gecerleme faaliyetleri, test seviyeleri, basarı kriterleri',
    def_req_verify:    base + 'Savunma SRS/IRS gereksinim dogrulama: her gereksinim icin dogru test yontemini ata, izlenebilirlik olustur',
    def_int_test:      base + 'Savunma alt sistem entegrasyon test planı: arayuz testleri, veri akısı, hata durumları, gecis kriterleri',
    def_env_test:      base + 'MIL-STD-810 cevresel test planı: termal, titresim, nem, toz, sarsıntı test prosedurlerini olustur',
    def_interface:     base + 'Savunma sistemi ICD/IRS arayuz test senaryoları: veri formati, zamanlama, hata islemesi dogrulaması',
    def_safety:        base + 'Emniyet kritik fonksiyon analizi: tehlike tanımlama, risk sınıflandırma, azaltma onlemleri ve test',
    def_protocol_test: base + 'MIL-STD-1553 veya ARINC veri yolu protokol test senaryoları: mesaj dogrulaması, hata enjeksiyonu',
    def_fat:           base + 'Fabrika/Saha Kabul Test proseduru: hazırlık, test adımları, gecis/basarısızlık kriterleri, kayıt formu',
    def_regression:    base + 'Savunma yazılım guncelleme regresyon test planı: etkilenen bilesenler, kritik fonksiyon testleri',
    def_cybersec:      base + 'Savunma sistemi siber guvenlik test planı: sızma testi senaryoları, TEMPEST, veri koruma kontrolleri',
  }
  return map[toolId] || base + 'Analiz et ve test onerileri sun.'
}
